### ISSUE TITLE
Create Command Center frontend

### ISSUE THREAD

**Issue by elohhim** [OskiKovski/WSDBusEnforcer#2]
![centrumdowodzenia-front](https://user-images.githubusercontent.com/5962410/49389472-af7fb400-f726-11e8-837e-55b620f17956.png)

**Comment by Mrooweq** [comment]
na razie wygląda to tak:

![commandcenter](https://user-images.githubusercontent.com/22622212/49543757-4f7d3f00-f8d9-11e8-9250-425c6dc3505a.png)

potrzebuję aby backend wystawił usługę, która bedzie zwracac cos takiegos:

{
            buses: [
                {
                    id: '523',
                    name: 'Autobus 523',
                    position: [52.253354, 20.996054]
                },
                {
                    id: '162',
                    name: 'Autobus 162',
                    position: [52.252106, 20.998135]
                },
                {
                    id: '20',
                    name: 'Tramwaj 20',
                    position: [52.253866, 21.000045]
                }
            ],
            policeCars: [
                {
                    id: '007',
                    name: '007',
                    position: [52.255094, 20.997438]
                },
                {
                    id: 'W11',
                    name: 'W 11',
                    position: [52.254923, 20.995979]
                }
            ]
        }

**Comment by Mrooweq** [comment]
na chwilę obecną front znajdziemy na branchu center-app

1. zeby uruchomic projekt trzeba zainstalowac node.js oraz npm (ten ostatni trzeba tez dodac do zmiennych srodowiskowych)  
2. w naszym projekcie wbijamy do pliku MainView.js i zakomentowujemy linijke... 

this.setMock(); 

...bo to od niej zalezy czy bicie na serwer bedzie realne czy mockowane
3. w naszym projekcie wbijamy do pliku Constants.js i ustawiamy url serwera (podejrzewam ze przy biciu do serwera pojawi sie problem z cross originem czy cos takiego, ale to chyba po stronie backendu cos trzeba ustawic w kodzie zeby zapytania przechodziły)
4. wbijamy konsolą w folder 'WSDBusEnforcer\center-front' i wywolujemy komendy:

npm install //to jest wymagane tylko za pierwszym razem
npm run start

5. front uruchomi sie na localhost:3000, a zapytanie http bedzie automatycznie wykonywac sie co 5 sekund

**Comment by elohhim** [comment]
Can you do a little layout work? Simply make map broader and lists slimmer. Nothing fancy.
